--liquibase formatted sql
--changeset kbielecki:1

CREATE TABLE details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_hour INT NOT NULL,
    weight DECIMAL(10, 2) NOT NULL,
    horse_power INT NOT NULL,
    category VARCHAR(255) NOT NULL
);

CREATE TABLE machine (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price_per_day DECIMAL(10, 2) NOT NULL,
    is_rented BOOLEAN NOT NULL,
    condition VARCHAR(255) NOT NULL,
    details_id BIGINT,
    FOREIGN KEY (details_id) REFERENCES details(id)
);

