--liquibase formatted sql
--changeset kbielecki:4

CREATE TABLE rents (
   rent_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
   user_id BIGINT NOT NULL,
   machine_id BIGINT NOT NULL,
   rented_date TIMESTAMP WITHOUT TIME ZONE NOT NULL
);