--liquibase formatted sql
--changeset kbielecki:3

CREATE TABLE rent_history (
  rent_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
   user_id BIGINT,
   machine_id BIGINT,
   rented_date TIMESTAMP WITHOUT TIME ZONE,
   returned_date TIMESTAMP WITHOUT TIME ZONE
);